name: Prepare release

on:
  workflow_dispatch:
    inputs:
      pre-release:
        required: false
        type: boolean
        default: false
        description: "This release will be labeled as non-production ready"
      stage:
        description: 'Prepare or publish a release'
        required: true
        default: 'prepare'
        type: choice
        options:
          - prepare
          - publish
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  prepare:
    if: (inputs.stage == 'prepare' || false) || (github.event.pull_request.merged && ! contains(github.event.pull_request.labels.*.name, 'release'))
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare the next main release
        uses: Adyen/release-automation-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          develop-branch: main
          version-files: src/Adyen/Client.php README.md
          pre-release: ${{ inputs.pre-release || false }}
  publish:
    if: (inputs.stage == 'publish' || false) || (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release'))
    permissions:
      contents: write
    uses: Adyen/release-automation-action/.github/workflows/reusable-github-release.yml@v1.1.1
    with:
      release-title: My Random Library
      develop-branch: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
