name: Releases

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Prepare or publish a release'
        required: true
        default: 'prepare'
        type: choice
        options:
          - prepare
          - publish
      pre-release:
        required: false
        type: boolean
        default: false
        description: "This release will be labeled as non-production ready"
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  releases:
    permissions:
      contents: write
      pull-requests: write
    uses: Adyen/release-automation-action/.github/workflows/reusable-release.yml@single-reusable-workflow
    with:
      release-title: My Random Library
      develop-branch: main
      version-files: package.json
      stage: ${{ inputs.stage || 'prepare' }}
      pre-release: ${{ inputs.pre-release || false }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
