name: Release management

on:
  workflow_dispatch:
    inputs:
      pre-release:
        required: false
        type: boolean
        default: false
        description: "This release will be labeled as non-production ready"
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  releases:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: Adyen/release-automation-action@single-reusable-workflow
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          develop-branch: main
          version-files: package.json
          pre-release: ${{ inputs.pre-release || false }}
          release-title: My Random Library
