name: Releases

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  releases:
    permissions:
      contents: write
      pull-requests: write
    uses: Adyen/release-automation-action/.github/workflows/reusable-release.yml@single-reusable-workflow
    with:
      release-title: My Random Library
      develop-branch: main
      version-files: package.json
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
